# -*- coding: utf-8 -*-
"""
Palette directions for the TACT Bedek marketing brand.

Specified in OKLCH, compiled to hex. Why OKLCH: its L is *perceived*
lightness, so two colours that share an L carry equal visual weight even at
different hues -- which is the whole trick behind bridging the emerald app
(H 169) and the indigo app (H 285) without one swamping the other.

Anchors we are bridging between:
    emerald app brand   oklch(0.579 0.113 169)  #0F8F6E
    indigo  app brand   oklch(0.550 0.113 285)  #6B67B0
    TACT steel-blue     oklch(0.340 0.068 256)  #1F3A5F

    python palette.py   -> directions.json (all four) + tokens.css (chosen)
"""
import io, json, os, sys

sys.stdout.reconfigure(encoding="utf-8")  # Hebrew dies on cp1252 otherwise

# Paths resolve against this file, never the caller's cwd -- these are run as
# `python brand/palette/palette.py` from the brand root.
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from oklch import oklch

EMERALD_H, INDIGO_H, STEEL_H = 169.0, 285.0, 256.0

# Chosen 2026-08-25. The other three stay in this file on purpose: they are the
# record of what was considered, and contrast.py keeps gating all four, so a
# later edit to the shared ramp() cannot quietly break one we might return to.
CHOSEN = "bridge"


def ramp(bh, bc, bl, accent, canvas_h, name, title, rationale, note):
    """One direction. `accent` is (L, C, H) for the CTA colour."""
    al, ac, ah = accent
    return {
        "name": name, "title": title, "rationale": rationale, "note": note,
        "colors": {
            # identity -- the only large filled areas of colour
            "brand":      oklch(bl,        bc,        bh),
            "brandDeep":  oklch(bl - 0.08, bc,        bh),
            "brandInk":   oklch(0.30,      bc * 0.75, bh),
            "brandSoft":  oklch(0.955,     bc * 0.22, bh),
            # the one action you want taken
            "accent":     oklch(al,        ac,        ah),
            "accentDeep": oklch(al - 0.10, ac,        ah),
            "accentSoft": oklch(0.955,     ac * 0.22, ah),
            # grounds
            "canvas":     oklch(0.982, 0.006, canvas_h),
            "surface":    "#FFFFFF",
            "mist":       oklch(0.958, 0.010, canvas_h),
            "border":     oklch(0.905, 0.012, canvas_h),
            # text -- never pure black, always tinted toward the brand hue
            "inkStrong":  oklch(0.245, 0.022, bh),
            "inkSoft":    oklch(0.470, 0.020, bh),
            "inkFaint":   oklch(0.600, 0.016, bh),
            # the two products, always shown in their real app colours
            "appUser":     oklch(0.550, 0.113, INDIGO_H),
            "appCustomer": oklch(0.579, 0.113, EMERALD_H),
        },
    }


def tokens_css(d):
    """The chosen direction, compiled for the site. Never hand-edit the output."""
    rows = "\n".join("  --{}: {};".format(k, v) for k, v in d["colors"].items())
    return (
        "/* GENERATED by brand/palette/palette.py -- do not hand-edit.\n"
        "   Direction: {} ({}). Regenerate with `python palette.py`.\n"
        "   Every pair is gated by contrast.py against WCAG AA. */\n"
        ":root {{\n{}\n}}\n"
    ).format(d["title"], d["name"], rows)


DIRECTIONS = [
    ramp(
        bh=227, bc=0.105, bl=0.500, accent=(0.660, 0.150, 62), canvas_h=227,
        name="bridge", title="א׳ · גשר",
        rationale="גוון 227 — נקודת האמצע המדויקת בין האמרלד של הדייר (169) לאינדיגו של איש החברה (285). כחול־טורקיז שקורא כשייך לשתי האפליקציות בלי להיות אף אחת מהן. האקסנט ענבר חם, כי CTA צריך להיות הצבע החם היחיד בעמוד.",
        note="הכי נאמן לבקשה \"פלטה שמשלבת\". החיסרון: מתרחק מה-steel-blue של TACT.",
    ),
    ramp(
        bh=STEEL_H, bc=0.070, bl=0.340, accent=(0.579, 0.113, EMERALD_H), canvas_h=60,
        name="anchor", title="ב׳ · עוגן TACT",
        rationale="ה-steel-blue של TACT הוא צבע המבנה, על רקע ה-cream החם של המותג. האקסנט הוא בדיוק האמרלד של אפליקציית הדייר — כלומר ה-CTA באתר הוא הצבע שהדייר יראה אחר כך במכשיר.",
        note="הכי חזק מבחינת שיוך לקבוצה. הכי מרוסן — ויש שיגידו שמרני.",
    ),
    ramp(
        bh=272, bc=0.095, bl=0.400, accent=(0.660, 0.155, 45), canvas_h=272,
        name="contrast", title="ג׳ · ניגוד",
        rationale="אינדיגו־נייבי עמוק (272, קרוב לאפליקציית איש החברה) מול אקסנט כתום־ענבר. פער הגוונים הגדול ביותר מבין הארבעה — וזה בדיוק מה שדף נחיתה צריך: כפתור אחד שאי אפשר לפספס.",
        note="הכי גבוה בהמרה, הכי נמוך בשיוך ל-TACT. נוטה ל\"טק\" ופחות ל\"בנייה\".",
    ),
    ramp(
        bh=200, bc=0.100, bl=0.480, accent=(0.550, 0.113, INDIGO_H), canvas_h=200,
        name="duet", title="ד׳ · דואט",
        rationale="ציאן־טורקיז כצבע המותג, ושתי האפליקציות נשארות בצבען האמיתי: האמרלד לדייר והאינדיגו לאיש החברה. במקום לטשטש את ההבדל — מציגים אותו כמערכת אחת עם שני ממשקים.",
        note="הכי מסביר את המוצר ויזואלית. דורש משמעת: שלושה צבעים בעמוד אחד נשברים בקלות.",
    ),
]


def chosen():
    return next(d for d in DIRECTIONS if d["name"] == CHOSEN)


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "directions.json")
    io.open(out, "w", encoding="utf-8").write(
        json.dumps(DIRECTIONS, ensure_ascii=False, indent=2))
    io.open(os.path.join(HERE, "tokens.css"), "w", encoding="utf-8").write(tokens_css(chosen()))

    for d in DIRECTIONS:
        c = d["colors"]
        mark = "   <-- CHOSEN" if d["name"] == CHOSEN else ""
        print("{:10} brand {}  accent {}  canvas {}{}".format(
            d["name"], c["brand"], c["accent"], c["canvas"], mark))
    print("\nwrote directions.json + tokens.css")
